name: "Terraform Dev Plan"

on:
  push:
    branches:
      - main
    paths:
      - 'secure-cloud-lab-dev/**'

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: "Terraform Plan (Dev)"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./secure-cloud-lab-dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          echo "Sprawdzam poprawnosc srodowiska..."
          echo "Account ID (Target): 781007641435"
          echo "Region: eu-north-1"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::781007641435:role/GitHubActions-Terraform-Role"
          aws-region: "eu-north-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
